#!/bin/sh

[ ! -d /dev/pts ] && mkdir -p /dev/pts
[ ! -d /dev/shm ] && mkdir -p /dev/shm

mount -a

# Parse command line options
for arg in $(cat /proc/cmdline); do
   case $arg in
   ip=*)
       IPOPTS=${arg#ip=}
       ;;
   slope=*)
       export INSTALL_SLOPE=${arg#slope=}
       ;;
   esac
done

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

echo Starting syslogd
syslogd -f /etc/syslog.conf

if [ -e /sbin/depmod ]; then
    echo Updating module dependencies
    depmod -a
fi

if [ -e /etc/modules ]; then
    echo Loading modules
    sh /etc/modules.load
fi

echo Starting telnetd
/usr/sbin/telnetd -l /bin/ash

echo Starting sshd
/sbin/sshd -f /etc/ssh/sshd_config

echo Setting hostname
HOSTNAME=`cat /etc/hostname`
/bin/hostname ${HOSTNAME}

echo Setting up network interface
ifup lo
DEVICE=eth0
if [ -z "${IPOPTS}" ]; then
    IPOPTS=dhcp
fi
case ${IPOPTS} in
    dhcp)
        ifup ${DEVICE}
        ;;
    none)
        ;;
    *)
	# When BOOTIF is specified then identify the device by MAC
	if [ -n "${BOOTIF}" ]; then
	    MAC=`echo ${BOOTIF#*-} | sed -r 's/[-]+/:/g'`
	    DEVICE=`ifconfig -a | grep -i ${MAC} | awk '{print $1}'`
	fi

        # Try and set the IP and Gateway based on the complex ip= parameter
	IP=`echo ${IPOPTS} | awk 'BEGIN {FS=":"}{print $1}'`
	if [ -n "${IP}" ]; then
            ifconfig ${DEVICE} ${IP} netmask 255.255.255.0
        fi
        GW=`echo ${IPOPTS} | awk 'BEGIN {FS=":"}{print $2}'`
	if [ -n "${GW}" ]; then
	    route add default gw ${GW}
        fi
	echo ""
        ;;
esac

# create bridge and bind to eth0
brctl addbr br0
brctl addif br0 eth0
brctl setfd br0 0
brctl sethello br0 1
brctl stp br0 no
ifup br0

if [ -e /dev/tun ]; then
   mkdir -p /dev/net
   ln -s /dev/tun /dev/net/tun
fi

# NFS Mount points
mount -a

# Service init scripts
chmod 655 /etc/init/*
for init in `find /etc/init/ -name \*.init`
do
    echo "[`date`]: Starting $init"
    /bin/sh $init
done

# Optional user script,  this should always run last
sh /etc/rc.local
