#!/bin/sh

if [ "$IFACE" == "lo" ]; then
   exit 0
fi

IPADDR=`ip address show $IFACE | awk '/inet / {print $2}' | cut -d/ -f1`
if [ -z "$IPADDR" ]; then
	IPADDR="0.0.0.0"
fi

NETMASK=`ifconfig $IFACE | awk -F: '/Mask:/ {print $4}'`
if [ -z "$NETMASK" ];then
	NETMASK="0.0.0.0"
fi

GW=`route -n | grep $IFACE | awk '{print $2}'`
if [ -z "$GW" ];then
	GW="0.0.0.0"
fi

sed -i -r 's/Address: (\b[0-9]{1,3}\.){3}[0-9]{1,3}\b/Address: '$IPADDR/ /etc/issue
sed -i -r 's/Netmask: (\b[0-9]{1,3}\.){3}[0-9]{1,3}\b/Netmask: '$NETMASK/ /etc/issue
sed -i -r 's/Gateway: (\b[0-9]{1,3}\.){3}[0-9]{1,3}\b/Gateway: '$GW/ /etc/issue

