export PDK := ${BASE}/../../pdk
VPDU_EMBEDDED_ROOTFS = ${VPDU_BASE}/embedded_rootfs
VPDUSERV = ${VPDU_BASE}/vpduserv

.PHONY: platform-specific
platform-specific:
	@if [ ! -d ${ROOT}/usr/pdusim/snmpdata/${TARGETNAME} ];then mkdir -p ${ROOT}/usr/pdusim/snmpdata/${TARGETNAME};fi
	@cp ${BASE}/data/* ${ROOT}/usr/pdusim/snmpdata/${TARGETNAME}/
	@cp -r ${VPDU_EMBEDDED_ROOTFS}/etc/*  ${ROOT}/etc/

include ${PDK}/Makefile
