#!/bin/sh

device=$1
interval=$2
force=$3
index=1
hwaddr=`ip address show br0 | awk '/ether/ {print $2}'`
while [ 1 ]
do
    msg="[`date`][$device][$hwaddr]: Identity `hostname`"
    logger -s $msg
    echo $msg > /dev/tty1
    sleep 1
    if [ "x$force" != "x1" ]; then
        if [ $index == $interval ]; then
            exit 0
        fi
        index=`expr $index + 1`
    fi
done
